name: Devious Export
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: Windows, os: windows-latest, target: Win64 }
        - { name: macOS, os: macos-latest, target: Darwin }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          combine: true
          target: ${{ matrix.config.target }}

      - name: Force Upload
        uses: actions/upload-artifact@v4
        with:
          name: DeviousMod-${{ matrix.config.name }}
          path: "**/*.geode"
