name: Devious Export
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: Windows, os: windows-latest }
        - { name: macOS, os: macos-latest }
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod-${{ matrix.config.name }}
          path: "**/*.geode"
